require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/**'
    - '*.gemspec'
  TargetRubyVersion: 2.5

# -----------------------------------------------------------------------------
#                                   RSPEC

RSpec:
  Include:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MissingExampleGroupArgument:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

# -----------------------------------------------------------------------------
#                                   Layout

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# -----------------------------------------------------------------------------
#                                    Lint

#
# False positives:
#   * expect { something }.to change { something } often triggers this
#
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

# -----------------------------------------------------------------------------
#                                   Metrics

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# -----------------------------------------------------------------------------
#                                   Style

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

#
# Both styles or mixtures are reasonable
#
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false

#
# Would be better but unlikely...
#
Style/Documentation:
  Enabled: false

#
# Okay for conditions, but false positive in return statements (e.g. APIs)
#
Style/DoubleNegation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

#
# Quick single line rescues in specs
#
Style/RescueModifier:
  Exclude:
    - 'spec/**/*_spec.rb'

#
# Quick single line rescues in specs
#
Style/RescueStandardError:
  Exclude:
    - 'spec/**/*_spec.rb'

#
# Often used pattern in chaining subjects in specs
#
Style/Semicolon:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/SignalException:
  EnforcedStyle: only_raise

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
